ysomekey: "somevalue"
ylocation:
    protocol: "http"
    host: "localhosts"
    port: 8080
    path: "/some/path"
    jedis:
        - Yoda
        - Qui-Gon Jinn
        - Obi-Wan Kenobi
        - Luke Skywalker
